version: '3'

services:
    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: lernfair_dev
