import { pupil_schooltype_enum as SchoolType } from '@prisma/client';

export const SchoolTypeMap: Record<string, SchoolType> = {
    grundschule: 'grundschule',
    gesamtschule: 'gesamtschule',
    hauptschule: 'hauptschule',
    realschule: 'realschule',
    gymnasium: 'gymnasium',
    förderschule: 'f_rderschule',
    berufsschule: 'berufsschule',
    mittelschule: 'mittelschule',
    oberschule: 'oberschule',
    sekundarschule: 'sekundarschule',
    stadtteilschule: 'stadtteilschule',
    berufsfachschule: 'berufsfachschule',
    fachoberschule: 'fachoberschule',
    berufsoberschule: 'berufsoberschule',
    oberstufenzentrum: 'oberstufenzentrum',
    fachschule: 'fachschule',
    abendschule_vhs: 'abendschule_vhs',
    berufskolleg: 'berufskolleg',
    beruflichesgymnasium: 'beruflichesgymnasium',
    uni_studienkolleg: 'uni_studienkolleg',
    auslandsschule: 'auslandsschule',
    privatschule: 'privatschule',
    other: 'other',
};

export const schoolTypeSearchStrings: Record<SchoolType, string[]> = {
    grundschule: ['grundschule'],
    berufsschule: ['berufsschule'],
    mittelschule: ['mittelschule', 'mittelstufenschule'],
    sekundarschule: ['sekundarschule'],
    stadtteilschule: ['stadtteilschule'],
    berufsfachschule: ['berufsfachschule', 'bfs'],
    fachoberschule: ['fachoberschule', 'fos'],
    berufsoberschule: ['berufsoberschule', 'bos'],
    oberstufenzentrum: ['oberstufenzentrum'],
    abendschule_vhs: ['abendschule', 'vhs', 'fernstudium', 'abendgymnasium', 'weiterbildungskolleg'],
    berufskolleg: ['berufskolleg'],
    oberschule: ['oberschule'],
    f_rderschule: ['förderschule'],
    beruflichesgymnasium: ['berufliches gymnasium', 'fachgymnasium'],
    uni_studienkolleg: ['studienkolleg', 'universität'],
    fachschule: ['fachschule'],
    hauptschule: ['hauptschule'],
    gesamtschule: ['gesamtschule', 'integrierte sekundarschule'],
    realschule: ['realschule'],
    gymnasium: ['gymnasium'],
    auslandsschule: [],
    privatschule: ['montessori', 'waldorf', 'privatschule', 'ersatzschule'],
    other: [],
};
