import {MigrationInterface, QueryRunner} from "typeorm";

export class AddUpdatedAtInCoC1635874676579 implements MigrationInterface {
    name = 'AddUpdatedAtInCoC1635874676579'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "certificate_of_conduct" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "project_match"."dissolveReason" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_match" ALTER COLUMN "dissolveReason" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil_tutoring_interest_confirmation_request"."reminderSentDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil_tutoring_interest_confirmation_request" ALTER COLUMN "reminderSentDate" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "verification" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "verifiedAt" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "authToken" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "authTokenSent" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."lastUpdatedSettingsViaBlocker" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "lastUpdatedSettingsViaBlocker" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."teacherEmailAddress" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "teacherEmailAddress" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "match"."dissolveReason" IS NULL`);
        await queryRunner.query(`ALTER TABLE "match" ALTER COLUMN "dissolveReason" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "verification" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "verifiedAt" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "authToken" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "authTokenSent" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "project_field_with_grade_restriction"."min" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" ALTER COLUMN "min" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "project_field_with_grade_restriction"."max" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" ALTER COLUMN "max" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "verification" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "verifiedAt" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "authToken" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "authTokenSent" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."wasJufoParticipant" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "wasJufoParticipant" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."hasJufoCertificate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "hasJufoCertificate" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."jufoPastParticipationInfo" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "jufoPastParticipationInfo" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."jufoPastParticipationConfirmed" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "jufoPastParticipationConfirmed" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."isUniversityStudent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "isUniversityStudent" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentJufoAlumniScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentJufoAlumniScreeningInvitationDate" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentScreeningInvitationDate" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentInstructorScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentInstructorScreeningInvitationDate" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastUpdatedSettingsViaBlocker" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastUpdatedSettingsViaBlocker" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "verification" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "verifiedAt" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "authToken" SET DEFAULT null`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "authTokenSent" SET DEFAULT null`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "authTokenSent" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "authToken" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "verifiedAt" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mentor" ALTER COLUMN "verification" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "mentor"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastUpdatedSettingsViaBlocker" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastUpdatedSettingsViaBlocker" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentInstructorScreeningInvitationDate" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentInstructorScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentScreeningInvitationDate" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "lastSentJufoAlumniScreeningInvitationDate" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."lastSentJufoAlumniScreeningInvitationDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "isUniversityStudent" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."isUniversityStudent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "jufoPastParticipationConfirmed" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."jufoPastParticipationConfirmed" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "jufoPastParticipationInfo" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."jufoPastParticipationInfo" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "hasJufoCertificate" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."hasJufoCertificate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "wasJufoParticipant" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."wasJufoParticipant" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "authTokenSent" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "authToken" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "verifiedAt" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student" ALTER COLUMN "verification" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "student"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" ALTER COLUMN "max" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "project_field_with_grade_restriction"."max" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" ALTER COLUMN "min" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "project_field_with_grade_restriction"."min" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "authTokenSent" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "authToken" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "verifiedAt" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "screener" ALTER COLUMN "verification" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "screener"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "match" ALTER COLUMN "dissolveReason" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "match"."dissolveReason" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "teacherEmailAddress" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."teacherEmailAddress" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "lastUpdatedSettingsViaBlocker" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."lastUpdatedSettingsViaBlocker" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "authTokenSent" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."authTokenSent" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "authToken" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "verifiedAt" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."verifiedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil" ALTER COLUMN "verification" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil"."verification" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pupil_tutoring_interest_confirmation_request" ALTER COLUMN "reminderSentDate" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "pupil_tutoring_interest_confirmation_request"."reminderSentDate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "project_match" ALTER COLUMN "dissolveReason" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "project_match"."dissolveReason" IS NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_of_conduct" DROP COLUMN "updatedAt"`);
    }

}
