import {MigrationInterface, QueryRunner} from "typeorm";

export class AddCertificateOfConduct1636569290926 implements MigrationInterface {
    name = 'AddCertificateOfConduct1636569290926'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "bbb_meeting" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "meetingID" character varying NOT NULL, "meetingName" character varying, "attendeePW" character varying, "moderatorPW" character varying, "alternativeUrl" character varying, CONSTRAINT "PK_33f2c503196edee1b2e5899083f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_tag" ("id" SERIAL NOT NULL, "identifier" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, CONSTRAINT "PK_6c6a0ad4b5f67db91353e5b2ae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_275561ded9309f727f8e795bf1" ON "course_tag" ("identifier") `);
        await queryRunner.query(`CREATE TABLE "course_guest" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "token" character varying NOT NULL, "firstname" character varying NOT NULL, "lastname" character varying NOT NULL, "email" character varying NOT NULL, "courseId" integer, "inviterId" integer, CONSTRAINT "PK_f12462c16c543cf76ed1fa49289" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fb7b15823c3ed0fea3c508ac4" ON "course_guest" ("token") `);
        await queryRunner.query(`CREATE TYPE "course_category_enum" AS ENUM('revision', 'club', 'coaching')`);
        await queryRunner.query(`CREATE TYPE "course_coursestate_enum" AS ENUM('created', 'submitted', 'allowed', 'denied', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "course" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "outline" character varying NOT NULL, "description" character varying NOT NULL, "imageKey" character varying, "category" "course_category_enum" NOT NULL, "courseState" "course_coursestate_enum" NOT NULL DEFAULT 'created', "screeningComment" character varying, "publicRanking" integer NOT NULL DEFAULT '0', "allowContact" boolean NOT NULL DEFAULT false, "correspondentId" integer, CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_attendance_log" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "attendedTime" integer, "ip" character varying, "pupilId" integer, "lectureId" integer, CONSTRAINT "PK_c3906899bb64b97b840ea1f2656" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lecture" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "start" TIMESTAMP NOT NULL, "duration" integer NOT NULL, "instructorId" integer, "subcourseId" integer, CONSTRAINT "PK_2abef7c1e52b7b58a9f905c9643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subcourse" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "minGrade" integer NOT NULL, "maxGrade" integer NOT NULL, "maxParticipants" integer NOT NULL, "joinAfterStart" boolean NOT NULL DEFAULT false, "published" boolean NOT NULL, "cancelled" boolean NOT NULL DEFAULT false, "courseId" integer, CONSTRAINT "PK_304edeed9f68de88999028fe80e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "school_state_enum" AS ENUM('bw', 'by', 'be', 'bb', 'hb', 'hh', 'he', 'mv', 'ni', 'nw', 'rp', 'sl', 'sn', 'st', 'sh', 'th', 'other')`);
        await queryRunner.query(`CREATE TYPE "school_schooltype_enum" AS ENUM('grundschule', 'gesamtschule', 'hauptschule', 'realschule', 'gymnasium', 'förderschule', 'berufsschule', 'other')`);
        await queryRunner.query(`CREATE TABLE "school" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "website" character varying, "emailDomain" character varying NOT NULL, "state" "school_state_enum" DEFAULT 'other', "schooltype" "school_schooltype_enum" NOT NULL DEFAULT 'other', "activeCooperation" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_57836c3fe2f2c7734b20911755e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b365d0ef66facdfeb842d45683" ON "school" ("website") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f3f92f9182a7fccc2858fd63cc" ON "school" ("emailDomain") `);
        await queryRunner.query(`CREATE TABLE "project_match" ("id" SERIAL NOT NULL, "uuid" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "dissolved" boolean NOT NULL DEFAULT false, "dissolveReason" integer DEFAULT null, "studentId" integer, "pupilId" integer, CONSTRAINT "UQ_PJ_MATCH" UNIQUE ("studentId", "pupilId"), CONSTRAINT "PK_14902d121cc871092943b3857e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_58dbaf83a377f347d9fab47fc5" ON "project_match" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "pupil_tutoring_interest_confirmation_request" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL DEFAULT 'pending', "token" character varying NOT NULL, "reminderSentDate" TIMESTAMP DEFAULT null, "pupilId" integer, CONSTRAINT "REL_5928ac6454eee0bfbdb8e538ef" UNIQUE ("pupilId"), CONSTRAINT "PK_5f3515ba0bd182b1cc34f06ef11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8108668f1658b14b9db299634e" ON "pupil_tutoring_interest_confirmation_request" ("token") `);
        await queryRunner.query(`CREATE TYPE "pupil_state_enum" AS ENUM('bw', 'by', 'be', 'bb', 'hb', 'hh', 'he', 'mv', 'ni', 'nw', 'rp', 'sl', 'sn', 'st', 'sh', 'th', 'other')`);
        await queryRunner.query(`CREATE TYPE "pupil_schooltype_enum" AS ENUM('grundschule', 'gesamtschule', 'hauptschule', 'realschule', 'gymnasium', 'förderschule', 'berufsschule', 'other')`);
        await queryRunner.query(`CREATE TYPE "pupil_projectfields_enum" AS ENUM('Arbeitswelt', 'Biologie', 'Chemie', 'Geo-und-Raumwissenschaften', 'Mathematik/Informatik', 'Physik', 'Technik')`);
        await queryRunner.query(`CREATE TYPE "pupil_languages_enum" AS ENUM('Albanisch', 'Arabisch', 'Armenisch', 'Aserbaidschanisch', 'Bosnisch', 'Bulgarisch', 'Chinesisch', 'Deutsch', 'Englisch', 'Französisch', 'Italienisch', 'Kasachisch', 'Kurdisch', 'Polnisch', 'Portugiesisch', 'Russisch', 'Türkisch', 'Spanisch', 'Ukrainisch', 'Vietnamesisch', 'Andere')`);
        await queryRunner.query(`CREATE TYPE "pupil_learninggermansince_enum" AS ENUM('>4', '2-4', '1-2', '<1')`);
        await queryRunner.query(`CREATE TYPE "pupil_registrationsource_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TABLE "pupil" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstname" character varying, "lastname" character varying, "active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "verification" character varying DEFAULT null, "verifiedAt" TIMESTAMP DEFAULT null, "authToken" character varying DEFAULT null, "authTokenUsed" boolean NOT NULL DEFAULT false, "authTokenSent" TIMESTAMP DEFAULT null, "wix_id" character varying NOT NULL, "wix_creation_date" TIMESTAMP NOT NULL, "state" "pupil_state_enum" NOT NULL DEFAULT 'other', "schooltype" "pupil_schooltype_enum" NOT NULL DEFAULT 'other', "msg" character varying, "grade" character varying, "newsletter" boolean NOT NULL DEFAULT false, "isPupil" boolean NOT NULL DEFAULT false, "subjects" character varying, "openMatchRequestCount" integer NOT NULL DEFAULT '1', "isParticipant" boolean NOT NULL DEFAULT true, "isProjectCoachee" boolean NOT NULL DEFAULT false, "projectFields" "pupil_projectfields_enum" array NOT NULL DEFAULT '{}', "isJufoParticipant" character varying NOT NULL DEFAULT 'unsure', "openProjectMatchRequestCount" integer NOT NULL DEFAULT '1', "projectMemberCount" integer NOT NULL DEFAULT '1', "languages" "pupil_languages_enum" array NOT NULL DEFAULT '{}', "learningGermanSince" "pupil_learninggermansince_enum", "matchingPriority" integer NOT NULL DEFAULT '0', "lastUpdatedSettingsViaBlocker" TIMESTAMP DEFAULT null, "teacherEmailAddress" character varying DEFAULT null, "registrationSource" "pupil_registrationsource_enum" NOT NULL DEFAULT '0', "schoolId" integer, CONSTRAINT "PK_34f2dbae733affb8884c2255c21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_24d523169870b7e80f9e68aad3" ON "pupil" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_90fde657ec008e61a5b07947b3" ON "pupil" ("verification") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5ff14bcaf5fdce75691fa8f34a" ON "pupil" ("authToken") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_16c46adbb2885e591364e476e5" ON "pupil" ("wix_id") `);
        await queryRunner.query(`CREATE TYPE "match_source_enum" AS ENUM('imported', 'matchedexternal', 'matchedinternal')`);
        await queryRunner.query(`CREATE TABLE "match" ("id" SERIAL NOT NULL, "uuid" character varying NOT NULL, "dissolved" boolean NOT NULL DEFAULT false, "dissolveReason" integer DEFAULT null, "proposedTime" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "feedbackToPupilMail" boolean NOT NULL DEFAULT false, "feedbackToStudentMail" boolean NOT NULL DEFAULT false, "followUpToPupilMail" boolean NOT NULL DEFAULT false, "followUpToStudentMail" boolean NOT NULL DEFAULT false, "source" "match_source_enum" NOT NULL DEFAULT 'matchedinternal', "studentId" integer, "pupilId" integer, CONSTRAINT "UQ_MATCH" UNIQUE ("studentId", "pupilId"), CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65a3ec8c0aa6c3c9c04f5b53e3" ON "match" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "screener" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstname" character varying, "lastname" character varying, "active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "verification" character varying DEFAULT null, "verifiedAt" TIMESTAMP DEFAULT null, "authToken" character varying DEFAULT null, "authTokenUsed" boolean NOT NULL DEFAULT false, "authTokenSent" TIMESTAMP DEFAULT null, "password" character varying NOT NULL, "verified" boolean DEFAULT false, "oldNumberID" integer, CONSTRAINT "UQ_96dc11de485d62615e78a875293" UNIQUE ("oldNumberID"), CONSTRAINT "PK_3a023b02ed01df4a6956af1ea94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_29a6207bc70a2b9e6731d66bcf" ON "screener" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c9e25ecca022d0d6cd401d9e5e" ON "screener" ("verification") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b858e5a35c51a4dbf6922025e7" ON "screener" ("authToken") `);
        await queryRunner.query(`CREATE TABLE "screening" ("id" SERIAL NOT NULL, "success" boolean NOT NULL, "comment" character varying, "knowsCoronaSchoolFrom" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "screenerId" integer, "studentId" integer, CONSTRAINT "REL_dfb78fd7887c69e3c52e002083" UNIQUE ("studentId"), CONSTRAINT "PK_5111bc526c9133721aeffb9a578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "instructor_screening" ("id" SERIAL NOT NULL, "success" boolean NOT NULL, "comment" character varying, "knowsCoronaSchoolFrom" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "screenerId" integer, "studentId" integer, CONSTRAINT "REL_e176665fa769d2e603d825f6fa" UNIQUE ("studentId"), CONSTRAINT "PK_e29a51f8dce0a07d2e1dba73636" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "project_field_with_grade_restriction_projectfield_enum" AS ENUM('Arbeitswelt', 'Biologie', 'Chemie', 'Geo-und-Raumwissenschaften', 'Mathematik/Informatik', 'Physik', 'Technik')`);
        await queryRunner.query(`CREATE TABLE "project_field_with_grade_restriction" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectField" "project_field_with_grade_restriction_projectfield_enum" NOT NULL, "min" integer DEFAULT null, "max" integer DEFAULT null, "studentId" integer NOT NULL, CONSTRAINT "UQ_PROJECT_FIELDS" UNIQUE ("projectField", "studentId"), CONSTRAINT "PK_9f450f4d0e5e20c5a0a6fee6dea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_coaching_screening" ("id" SERIAL NOT NULL, "success" boolean NOT NULL, "comment" character varying, "knowsCoronaSchoolFrom" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "screenerId" integer, "studentId" integer, CONSTRAINT "REL_565d757e2fd9a97fc3f30f5129" UNIQUE ("studentId"), CONSTRAINT "PK_4a1d3d3d6f0fa2b36c8347e357c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jufo_verification_transmission" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "uuid" character varying NOT NULL, "studentId" integer, CONSTRAINT "REL_1ceddec34e7b90cdbb85ff9738" UNIQUE ("studentId"), CONSTRAINT "PK_3e81acd237ad0b7e97003c835d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expertise_tag" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_4251b103cf2216af06b5c8625f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_29beceeebc3a1eae3d78939713" ON "expertise_tag" ("name") `);
        await queryRunner.query(`CREATE TYPE "expert_data_allowed_enum" AS ENUM('pending', 'yes', 'no')`);
        await queryRunner.query(`CREATE TABLE "expert_data" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "contactEmail" character varying NOT NULL, "description" character varying, "active" boolean NOT NULL DEFAULT false, "allowed" "expert_data_allowed_enum" NOT NULL DEFAULT 'pending', "studentId" integer, CONSTRAINT "REL_0bf0d1a1e138fd47f60e263524" UNIQUE ("studentId"), CONSTRAINT "PK_096e6e0f8fcc7e142b555fde91e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "concrete_notification" ("id" SERIAL NOT NULL, "userId" character varying NOT NULL, "notificationID" integer NOT NULL, "contextID" character varying, "context" json NOT NULL, "sentAt" TIMESTAMP NOT NULL, "state" integer NOT NULL, "error" character varying, CONSTRAINT "PK_830b05c48e7ba274a9e4bceced3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "mailjetTemplateId" integer, "description" character varying NOT NULL, "active" boolean NOT NULL, "recipient" integer NOT NULL, "onActions" text array NOT NULL, "category" text array NOT NULL, "cancelledOnAction" text array NOT NULL, "delay" integer, "interval" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "student_state_enum" AS ENUM('bw', 'by', 'be', 'bb', 'hb', 'hh', 'he', 'mv', 'ni', 'nw', 'rp', 'sl', 'sn', 'st', 'sh', 'th', 'other')`);
        await queryRunner.query(`CREATE TYPE "student_module_enum" AS ENUM('internship', 'seminar', 'other')`);
        await queryRunner.query(`CREATE TYPE "student_languages_enum" AS ENUM('Albanisch', 'Arabisch', 'Armenisch', 'Aserbaidschanisch', 'Bosnisch', 'Bulgarisch', 'Chinesisch', 'Deutsch', 'Englisch', 'Französisch', 'Italienisch', 'Kasachisch', 'Kurdisch', 'Polnisch', 'Portugiesisch', 'Russisch', 'Türkisch', 'Spanisch', 'Ukrainisch', 'Vietnamesisch', 'Andere')`);
        await queryRunner.query(`CREATE TYPE "student_registrationsource_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TABLE "student" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstname" character varying, "lastname" character varying, "active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "verification" character varying DEFAULT null, "verifiedAt" TIMESTAMP DEFAULT null, "authToken" character varying DEFAULT null, "authTokenUsed" boolean NOT NULL DEFAULT false, "authTokenSent" TIMESTAMP DEFAULT null, "wix_id" character varying NOT NULL, "wix_creation_date" TIMESTAMP NOT NULL, "phone" character varying, "feedback" character varying, "newsletter" boolean NOT NULL DEFAULT false, "isStudent" boolean NOT NULL DEFAULT false, "subjects" character varying, "openMatchRequestCount" integer NOT NULL DEFAULT '1', "isInstructor" boolean NOT NULL DEFAULT false, "msg" character varying, "state" "student_state_enum" DEFAULT 'other', "university" character varying, "module" "student_module_enum", "moduleHours" integer, "isProjectCoach" boolean NOT NULL DEFAULT false, "wasJufoParticipant" character varying DEFAULT null, "hasJufoCertificate" boolean DEFAULT null, "jufoPastParticipationInfo" character varying DEFAULT null, "jufoPastParticipationConfirmed" boolean DEFAULT null, "isUniversityStudent" boolean DEFAULT null, "openProjectMatchRequestCount" integer NOT NULL DEFAULT '1', "sentJufoAlumniScreeningReminderCount" integer NOT NULL DEFAULT '0', "lastSentJufoAlumniScreeningInvitationDate" TIMESTAMP DEFAULT null, "supportsInDaZ" boolean, "languages" "student_languages_enum" array NOT NULL DEFAULT '{}', "sentScreeningReminderCount" integer NOT NULL DEFAULT '0', "lastSentScreeningInvitationDate" TIMESTAMP DEFAULT null, "sentInstructorScreeningReminderCount" integer NOT NULL DEFAULT '0', "lastSentInstructorScreeningInvitationDate" TIMESTAMP DEFAULT null, "lastUpdatedSettingsViaBlocker" TIMESTAMP DEFAULT null, "registrationSource" "student_registrationsource_enum" NOT NULL DEFAULT '0', CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a56c051c91dbe1068ad683f536" ON "student" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_34cbafcb0bcdfb2b6de9010acb" ON "student" ("verification") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4d0994b549167f69e3cec7c00" ON "student" ("authToken") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_545d0c66310ca5df98b4765cc7" ON "student" ("wix_id") `);
        await queryRunner.query(`CREATE TABLE "certificate_of_conduct" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "dateOfInspection" TIMESTAMP NOT NULL, "dateOfIssue" TIMESTAMP NOT NULL, "criminalRecords" boolean NOT NULL, "studentId" integer, CONSTRAINT "REL_11ea2a4aad67ab6428a6ca21b4" UNIQUE ("studentId"), CONSTRAINT "PK_95058dd1916a7fb5ff77170c374" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_participation_certificate" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "issuerId" integer, "pupilId" integer, "subcourseId" integer, CONSTRAINT "PK_ee8536af11485574445cf6c0b0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "log_logtype_enum" AS ENUM('misc', 'verificationRequets', 'verified', 'matchDissolve', 'projectMatchDissolve', 'fetchedFromWix', 'deActivate', 'updatePersonal', 'updateSubjects', 'updateProjectFields', 'accessedByScreener', 'updatedByScreener', 'updateStudentDescription', 'createdCourse', 'certificateRequest', 'cancelledCourse', 'cancelledSubcourse', 'createdCourseAttendanceLog', 'contactMentor', 'bbbMeeting', 'contactExpert', 'participantJoinedCourse', 'participantLeftCourse', 'participantJoinedWaitingList', 'participantLeftWaitingList', 'userAccessedCourseWhileAuthenticated', 'instructorIssuedCertificate', 'pupilInterestConfirmationRequestSent', 'pupilInterestConfirmationRequestReminderSent', 'pupilInterestConfirmationRequestStatusChange')`);
        await queryRunner.query(`CREATE TABLE "log" ("id" SERIAL NOT NULL, "logtype" "log_logtype_enum" NOT NULL DEFAULT 'misc', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user" character varying NOT NULL, "data" character varying NOT NULL, CONSTRAINT "PK_350604cbdf991d5930d9e618fbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "mentor_division_enum" AS ENUM('facebook', 'email', 'events', 'video', 'supervision')`);
        await queryRunner.query(`CREATE TYPE "mentor_expertise_enum" AS ENUM('language difficulties and communication', 'specialized expertise in subjects', 'educational and didactic expertise', 'technical support', 'self-organization')`);
        await queryRunner.query(`CREATE TABLE "mentor" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstname" character varying, "lastname" character varying, "active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "verification" character varying DEFAULT null, "verifiedAt" TIMESTAMP DEFAULT null, "authToken" character varying DEFAULT null, "authTokenUsed" boolean NOT NULL DEFAULT false, "authTokenSent" TIMESTAMP DEFAULT null, "wix_id" character varying NOT NULL, "wix_creation_date" TIMESTAMP NOT NULL, "division" "mentor_division_enum" array NOT NULL, "expertise" "mentor_expertise_enum" array NOT NULL, "subjects" character varying, "teachingExperience" boolean, "message" character varying, "description" character varying, "imageUrl" character varying, CONSTRAINT "PK_9fcebd0a40237e9b6defcbd9d74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e03cfa18e81812d44f5cdf9479" ON "mentor" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_704a7bf0ca9889bd5c4ea1a15b" ON "mentor" ("verification") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d6c74ee02bc266daf510d3ef2a" ON "mentor" ("authToken") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5c42dcf75b1abecf9860e54a12" ON "mentor" ("wix_id") `);
        await queryRunner.query(`CREATE TABLE "participation_certificate" ("id" SERIAL NOT NULL, "uuid" character varying NOT NULL, "subjects" character varying NOT NULL, "categories" character varying NOT NULL, "certificateDate" TIMESTAMP NOT NULL DEFAULT now(), "startDate" TIMESTAMP NOT NULL DEFAULT now(), "endDate" TIMESTAMP NOT NULL DEFAULT now(), "hoursPerWeek" numeric NOT NULL, "hoursTotal" numeric NOT NULL, "medium" character varying NOT NULL, "ongoingLessons" boolean NOT NULL DEFAULT false, "state" character varying NOT NULL DEFAULT 'manual', "signaturePupil" bytea, "signatureParent" bytea, "signatureLocation" character varying, "signatureDate" TIMESTAMP, "studentId" integer, "pupilId" integer, CONSTRAINT "PK_431b3e203adb26c29ecef120034" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5c7ebcd2f3fc7ed6022a478980" ON "participation_certificate" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "course_instructors_student" ("courseId" integer NOT NULL, "studentId" integer NOT NULL, CONSTRAINT "PK_aa54b28c5de0010f486dd0d72df" PRIMARY KEY ("courseId", "studentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54bce9a9a93ae130beaa70bb2f" ON "course_instructors_student" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_66b47860afa3098729925338c1" ON "course_instructors_student" ("studentId") `);
        await queryRunner.query(`CREATE TABLE "course_tags_course_tag" ("courseId" integer NOT NULL, "courseTagId" integer NOT NULL, CONSTRAINT "PK_3996cf424477234b88a0980fd39" PRIMARY KEY ("courseId", "courseTagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6261ad9de1fc5f06946095bf8" ON "course_tags_course_tag" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_af4499c3ae1153ac06782b2e5b" ON "course_tags_course_tag" ("courseTagId") `);
        await queryRunner.query(`CREATE TABLE "subcourse_instructors_student" ("subcourseId" integer NOT NULL, "studentId" integer NOT NULL, CONSTRAINT "PK_e41756ec54d1828c27b0a5dc055" PRIMARY KEY ("subcourseId", "studentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f0c594b9393bf4ca9ed368196" ON "subcourse_instructors_student" ("subcourseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b36e4eeff8040a09cc811dbb26" ON "subcourse_instructors_student" ("studentId") `);
        await queryRunner.query(`CREATE TABLE "subcourse_participants_pupil" ("subcourseId" integer NOT NULL, "pupilId" integer NOT NULL, CONSTRAINT "PK_7b8738e08eab7b5bf796f0eaf1b" PRIMARY KEY ("subcourseId", "pupilId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cde91c063947d1302d50c906dc" ON "subcourse_participants_pupil" ("subcourseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d9d98b6496554165e08ff61d" ON "subcourse_participants_pupil" ("pupilId") `);
        await queryRunner.query(`CREATE TABLE "subcourse_waiting_list_pupil" ("subcourseId" integer NOT NULL, "pupilId" integer NOT NULL, CONSTRAINT "PK_b35d059abbd7f4c4a1147f72ec9" PRIMARY KEY ("subcourseId", "pupilId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df9eb9663f8085da35f7ca5547" ON "subcourse_waiting_list_pupil" ("subcourseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bd25f377afc44f574f7ac3d09" ON "subcourse_waiting_list_pupil" ("pupilId") `);
        await queryRunner.query(`CREATE TABLE "expert_data_expertise_tags_expertise_tag" ("expertDataId" integer NOT NULL, "expertiseTagId" integer NOT NULL, CONSTRAINT "PK_bc62a3cbf8ed9f07fc7e43163d4" PRIMARY KEY ("expertDataId", "expertiseTagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73044a211048e72c2026425c81" ON "expert_data_expertise_tags_expertise_tag" ("expertDataId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a81e80d1d580b868ed36ca123" ON "expert_data_expertise_tags_expertise_tag" ("expertiseTagId") `);
        await queryRunner.query(`ALTER TABLE "course_guest" ADD CONSTRAINT "FK_4392726b6462358a809db822af4" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_guest" ADD CONSTRAINT "FK_a0843258a46daa7d91dc2cef917" FOREIGN KEY ("inviterId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_0682a6fe3bace3ed13377c1b1ca" FOREIGN KEY ("correspondentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_attendance_log" ADD CONSTRAINT "FK_acc59dc4321a888376f7fad5a3d" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "course_attendance_log" ADD CONSTRAINT "FK_927959c3480126ecdceeae26609" FOREIGN KEY ("lectureId") REFERENCES "lecture"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD CONSTRAINT "FK_2ca61c8451b53ad2da3c5f6432a" FOREIGN KEY ("instructorId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD CONSTRAINT "FK_087916363d2c5b483701d505a07" FOREIGN KEY ("subcourseId") REFERENCES "subcourse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse" ADD CONSTRAINT "FK_274b57f6af62ffadb80afcbae85" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_match" ADD CONSTRAINT "FK_ec8c8527004e4b21fa92dfde9f4" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_match" ADD CONSTRAINT "FK_2f269fd77a19a301eb7c9aaa6b6" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pupil_tutoring_interest_confirmation_request" ADD CONSTRAINT "FK_5928ac6454eee0bfbdb8e538ef8" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pupil" ADD CONSTRAINT "FK_ed2282d6491ddb708d5b8f60225" FOREIGN KEY ("schoolId") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_89d8d61ff2bcae46513788416e4" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_38770d911dab69557a913812f3f" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening" ADD CONSTRAINT "FK_c0b20c6342ac95d3b66c31ac30e" FOREIGN KEY ("screenerId") REFERENCES "screener"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "screening" ADD CONSTRAINT "FK_dfb78fd7887c69e3c52e0020838" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_screening" ADD CONSTRAINT "FK_ef1d3e862feda89b92fddcdbb34" FOREIGN KEY ("screenerId") REFERENCES "screener"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_screening" ADD CONSTRAINT "FK_e176665fa769d2e603d825f6fa3" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" ADD CONSTRAINT "FK_8cdc7fe37faa309976893b8ad07" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_coaching_screening" ADD CONSTRAINT "FK_91fa06e6e9aa04b5da93d034cae" FOREIGN KEY ("screenerId") REFERENCES "screener"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_coaching_screening" ADD CONSTRAINT "FK_565d757e2fd9a97fc3f30f51297" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jufo_verification_transmission" ADD CONSTRAINT "FK_1ceddec34e7b90cdbb85ff9738f" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expert_data" ADD CONSTRAINT "FK_0bf0d1a1e138fd47f60e2635247" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate_of_conduct" ADD CONSTRAINT "FK_11ea2a4aad67ab6428a6ca21b41" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" ADD CONSTRAINT "FK_d03c3421018dd300f5e9061ae87" FOREIGN KEY ("issuerId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" ADD CONSTRAINT "FK_585aa209315fc328d48af2765b4" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" ADD CONSTRAINT "FK_bc6a26ac82132b6e9f1d6de3e4c" FOREIGN KEY ("subcourseId") REFERENCES "subcourse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participation_certificate" ADD CONSTRAINT "FK_b8bb6da6b807a7b382218947647" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participation_certificate" ADD CONSTRAINT "FK_01437dc10f00eace91b0f93a805" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_instructors_student" ADD CONSTRAINT "FK_54bce9a9a93ae130beaa70bb2fa" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_instructors_student" ADD CONSTRAINT "FK_66b47860afa3098729925338c18" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_tags_course_tag" ADD CONSTRAINT "FK_d6261ad9de1fc5f06946095bf8c" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_tags_course_tag" ADD CONSTRAINT "FK_af4499c3ae1153ac06782b2e5b9" FOREIGN KEY ("courseTagId") REFERENCES "course_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_instructors_student" ADD CONSTRAINT "FK_3f0c594b9393bf4ca9ed3681967" FOREIGN KEY ("subcourseId") REFERENCES "subcourse"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_instructors_student" ADD CONSTRAINT "FK_b36e4eeff8040a09cc811dbb262" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_participants_pupil" ADD CONSTRAINT "FK_cde91c063947d1302d50c906dcd" FOREIGN KEY ("subcourseId") REFERENCES "subcourse"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_participants_pupil" ADD CONSTRAINT "FK_47d9d98b6496554165e08ff61d9" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_waiting_list_pupil" ADD CONSTRAINT "FK_df9eb9663f8085da35f7ca55471" FOREIGN KEY ("subcourseId") REFERENCES "subcourse"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcourse_waiting_list_pupil" ADD CONSTRAINT "FK_3bd25f377afc44f574f7ac3d09b" FOREIGN KEY ("pupilId") REFERENCES "pupil"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expert_data_expertise_tags_expertise_tag" ADD CONSTRAINT "FK_73044a211048e72c2026425c81c" FOREIGN KEY ("expertDataId") REFERENCES "expert_data"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expert_data_expertise_tags_expertise_tag" ADD CONSTRAINT "FK_8a81e80d1d580b868ed36ca1234" FOREIGN KEY ("expertiseTagId") REFERENCES "expertise_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expert_data_expertise_tags_expertise_tag" DROP CONSTRAINT "FK_8a81e80d1d580b868ed36ca1234"`);
        await queryRunner.query(`ALTER TABLE "expert_data_expertise_tags_expertise_tag" DROP CONSTRAINT "FK_73044a211048e72c2026425c81c"`);
        await queryRunner.query(`ALTER TABLE "subcourse_waiting_list_pupil" DROP CONSTRAINT "FK_3bd25f377afc44f574f7ac3d09b"`);
        await queryRunner.query(`ALTER TABLE "subcourse_waiting_list_pupil" DROP CONSTRAINT "FK_df9eb9663f8085da35f7ca55471"`);
        await queryRunner.query(`ALTER TABLE "subcourse_participants_pupil" DROP CONSTRAINT "FK_47d9d98b6496554165e08ff61d9"`);
        await queryRunner.query(`ALTER TABLE "subcourse_participants_pupil" DROP CONSTRAINT "FK_cde91c063947d1302d50c906dcd"`);
        await queryRunner.query(`ALTER TABLE "subcourse_instructors_student" DROP CONSTRAINT "FK_b36e4eeff8040a09cc811dbb262"`);
        await queryRunner.query(`ALTER TABLE "subcourse_instructors_student" DROP CONSTRAINT "FK_3f0c594b9393bf4ca9ed3681967"`);
        await queryRunner.query(`ALTER TABLE "course_tags_course_tag" DROP CONSTRAINT "FK_af4499c3ae1153ac06782b2e5b9"`);
        await queryRunner.query(`ALTER TABLE "course_tags_course_tag" DROP CONSTRAINT "FK_d6261ad9de1fc5f06946095bf8c"`);
        await queryRunner.query(`ALTER TABLE "course_instructors_student" DROP CONSTRAINT "FK_66b47860afa3098729925338c18"`);
        await queryRunner.query(`ALTER TABLE "course_instructors_student" DROP CONSTRAINT "FK_54bce9a9a93ae130beaa70bb2fa"`);
        await queryRunner.query(`ALTER TABLE "participation_certificate" DROP CONSTRAINT "FK_01437dc10f00eace91b0f93a805"`);
        await queryRunner.query(`ALTER TABLE "participation_certificate" DROP CONSTRAINT "FK_b8bb6da6b807a7b382218947647"`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" DROP CONSTRAINT "FK_bc6a26ac82132b6e9f1d6de3e4c"`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" DROP CONSTRAINT "FK_585aa209315fc328d48af2765b4"`);
        await queryRunner.query(`ALTER TABLE "course_participation_certificate" DROP CONSTRAINT "FK_d03c3421018dd300f5e9061ae87"`);
        await queryRunner.query(`ALTER TABLE "certificate_of_conduct" DROP CONSTRAINT "FK_11ea2a4aad67ab6428a6ca21b41"`);
        await queryRunner.query(`ALTER TABLE "expert_data" DROP CONSTRAINT "FK_0bf0d1a1e138fd47f60e2635247"`);
        await queryRunner.query(`ALTER TABLE "jufo_verification_transmission" DROP CONSTRAINT "FK_1ceddec34e7b90cdbb85ff9738f"`);
        await queryRunner.query(`ALTER TABLE "project_coaching_screening" DROP CONSTRAINT "FK_565d757e2fd9a97fc3f30f51297"`);
        await queryRunner.query(`ALTER TABLE "project_coaching_screening" DROP CONSTRAINT "FK_91fa06e6e9aa04b5da93d034cae"`);
        await queryRunner.query(`ALTER TABLE "project_field_with_grade_restriction" DROP CONSTRAINT "FK_8cdc7fe37faa309976893b8ad07"`);
        await queryRunner.query(`ALTER TABLE "instructor_screening" DROP CONSTRAINT "FK_e176665fa769d2e603d825f6fa3"`);
        await queryRunner.query(`ALTER TABLE "instructor_screening" DROP CONSTRAINT "FK_ef1d3e862feda89b92fddcdbb34"`);
        await queryRunner.query(`ALTER TABLE "screening" DROP CONSTRAINT "FK_dfb78fd7887c69e3c52e0020838"`);
        await queryRunner.query(`ALTER TABLE "screening" DROP CONSTRAINT "FK_c0b20c6342ac95d3b66c31ac30e"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_38770d911dab69557a913812f3f"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_89d8d61ff2bcae46513788416e4"`);
        await queryRunner.query(`ALTER TABLE "pupil" DROP CONSTRAINT "FK_ed2282d6491ddb708d5b8f60225"`);
        await queryRunner.query(`ALTER TABLE "pupil_tutoring_interest_confirmation_request" DROP CONSTRAINT "FK_5928ac6454eee0bfbdb8e538ef8"`);
        await queryRunner.query(`ALTER TABLE "project_match" DROP CONSTRAINT "FK_2f269fd77a19a301eb7c9aaa6b6"`);
        await queryRunner.query(`ALTER TABLE "project_match" DROP CONSTRAINT "FK_ec8c8527004e4b21fa92dfde9f4"`);
        await queryRunner.query(`ALTER TABLE "subcourse" DROP CONSTRAINT "FK_274b57f6af62ffadb80afcbae85"`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP CONSTRAINT "FK_087916363d2c5b483701d505a07"`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP CONSTRAINT "FK_2ca61c8451b53ad2da3c5f6432a"`);
        await queryRunner.query(`ALTER TABLE "course_attendance_log" DROP CONSTRAINT "FK_927959c3480126ecdceeae26609"`);
        await queryRunner.query(`ALTER TABLE "course_attendance_log" DROP CONSTRAINT "FK_acc59dc4321a888376f7fad5a3d"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_0682a6fe3bace3ed13377c1b1ca"`);
        await queryRunner.query(`ALTER TABLE "course_guest" DROP CONSTRAINT "FK_a0843258a46daa7d91dc2cef917"`);
        await queryRunner.query(`ALTER TABLE "course_guest" DROP CONSTRAINT "FK_4392726b6462358a809db822af4"`);
        await queryRunner.query(`DROP INDEX "IDX_8a81e80d1d580b868ed36ca123"`);
        await queryRunner.query(`DROP INDEX "IDX_73044a211048e72c2026425c81"`);
        await queryRunner.query(`DROP TABLE "expert_data_expertise_tags_expertise_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_3bd25f377afc44f574f7ac3d09"`);
        await queryRunner.query(`DROP INDEX "IDX_df9eb9663f8085da35f7ca5547"`);
        await queryRunner.query(`DROP TABLE "subcourse_waiting_list_pupil"`);
        await queryRunner.query(`DROP INDEX "IDX_47d9d98b6496554165e08ff61d"`);
        await queryRunner.query(`DROP INDEX "IDX_cde91c063947d1302d50c906dc"`);
        await queryRunner.query(`DROP TABLE "subcourse_participants_pupil"`);
        await queryRunner.query(`DROP INDEX "IDX_b36e4eeff8040a09cc811dbb26"`);
        await queryRunner.query(`DROP INDEX "IDX_3f0c594b9393bf4ca9ed368196"`);
        await queryRunner.query(`DROP TABLE "subcourse_instructors_student"`);
        await queryRunner.query(`DROP INDEX "IDX_af4499c3ae1153ac06782b2e5b"`);
        await queryRunner.query(`DROP INDEX "IDX_d6261ad9de1fc5f06946095bf8"`);
        await queryRunner.query(`DROP TABLE "course_tags_course_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_66b47860afa3098729925338c1"`);
        await queryRunner.query(`DROP INDEX "IDX_54bce9a9a93ae130beaa70bb2f"`);
        await queryRunner.query(`DROP TABLE "course_instructors_student"`);
        await queryRunner.query(`DROP INDEX "IDX_5c7ebcd2f3fc7ed6022a478980"`);
        await queryRunner.query(`DROP TABLE "participation_certificate"`);
        await queryRunner.query(`DROP INDEX "IDX_5c42dcf75b1abecf9860e54a12"`);
        await queryRunner.query(`DROP INDEX "IDX_d6c74ee02bc266daf510d3ef2a"`);
        await queryRunner.query(`DROP INDEX "IDX_704a7bf0ca9889bd5c4ea1a15b"`);
        await queryRunner.query(`DROP INDEX "IDX_e03cfa18e81812d44f5cdf9479"`);
        await queryRunner.query(`DROP TABLE "mentor"`);
        await queryRunner.query(`DROP TYPE "mentor_expertise_enum"`);
        await queryRunner.query(`DROP TYPE "mentor_division_enum"`);
        await queryRunner.query(`DROP TABLE "log"`);
        await queryRunner.query(`DROP TYPE "log_logtype_enum"`);
        await queryRunner.query(`DROP TABLE "course_participation_certificate"`);
        await queryRunner.query(`DROP TABLE "certificate_of_conduct"`);
        await queryRunner.query(`DROP INDEX "IDX_545d0c66310ca5df98b4765cc7"`);
        await queryRunner.query(`DROP INDEX "IDX_f4d0994b549167f69e3cec7c00"`);
        await queryRunner.query(`DROP INDEX "IDX_34cbafcb0bcdfb2b6de9010acb"`);
        await queryRunner.query(`DROP INDEX "IDX_a56c051c91dbe1068ad683f536"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`DROP TYPE "student_registrationsource_enum"`);
        await queryRunner.query(`DROP TYPE "student_languages_enum"`);
        await queryRunner.query(`DROP TYPE "student_module_enum"`);
        await queryRunner.query(`DROP TYPE "student_state_enum"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "concrete_notification"`);
        await queryRunner.query(`DROP TABLE "expert_data"`);
        await queryRunner.query(`DROP TYPE "expert_data_allowed_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_29beceeebc3a1eae3d78939713"`);
        await queryRunner.query(`DROP TABLE "expertise_tag"`);
        await queryRunner.query(`DROP TABLE "jufo_verification_transmission"`);
        await queryRunner.query(`DROP TABLE "project_coaching_screening"`);
        await queryRunner.query(`DROP TABLE "project_field_with_grade_restriction"`);
        await queryRunner.query(`DROP TYPE "project_field_with_grade_restriction_projectfield_enum"`);
        await queryRunner.query(`DROP TABLE "instructor_screening"`);
        await queryRunner.query(`DROP TABLE "screening"`);
        await queryRunner.query(`DROP INDEX "IDX_b858e5a35c51a4dbf6922025e7"`);
        await queryRunner.query(`DROP INDEX "IDX_c9e25ecca022d0d6cd401d9e5e"`);
        await queryRunner.query(`DROP INDEX "IDX_29a6207bc70a2b9e6731d66bcf"`);
        await queryRunner.query(`DROP TABLE "screener"`);
        await queryRunner.query(`DROP INDEX "IDX_65a3ec8c0aa6c3c9c04f5b53e3"`);
        await queryRunner.query(`DROP TABLE "match"`);
        await queryRunner.query(`DROP TYPE "match_source_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_16c46adbb2885e591364e476e5"`);
        await queryRunner.query(`DROP INDEX "IDX_5ff14bcaf5fdce75691fa8f34a"`);
        await queryRunner.query(`DROP INDEX "IDX_90fde657ec008e61a5b07947b3"`);
        await queryRunner.query(`DROP INDEX "IDX_24d523169870b7e80f9e68aad3"`);
        await queryRunner.query(`DROP TABLE "pupil"`);
        await queryRunner.query(`DROP TYPE "pupil_registrationsource_enum"`);
        await queryRunner.query(`DROP TYPE "pupil_learninggermansince_enum"`);
        await queryRunner.query(`DROP TYPE "pupil_languages_enum"`);
        await queryRunner.query(`DROP TYPE "pupil_projectfields_enum"`);
        await queryRunner.query(`DROP TYPE "pupil_schooltype_enum"`);
        await queryRunner.query(`DROP TYPE "pupil_state_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_8108668f1658b14b9db299634e"`);
        await queryRunner.query(`DROP TABLE "pupil_tutoring_interest_confirmation_request"`);
        await queryRunner.query(`DROP INDEX "IDX_58dbaf83a377f347d9fab47fc5"`);
        await queryRunner.query(`DROP TABLE "project_match"`);
        await queryRunner.query(`DROP INDEX "IDX_f3f92f9182a7fccc2858fd63cc"`);
        await queryRunner.query(`DROP INDEX "IDX_b365d0ef66facdfeb842d45683"`);
        await queryRunner.query(`DROP TABLE "school"`);
        await queryRunner.query(`DROP TYPE "school_schooltype_enum"`);
        await queryRunner.query(`DROP TYPE "school_state_enum"`);
        await queryRunner.query(`DROP TABLE "subcourse"`);
        await queryRunner.query(`DROP TABLE "lecture"`);
        await queryRunner.query(`DROP TABLE "course_attendance_log"`);
        await queryRunner.query(`DROP TABLE "course"`);
        await queryRunner.query(`DROP TYPE "course_coursestate_enum"`);
        await queryRunner.query(`DROP TYPE "course_category_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_8fb7b15823c3ed0fea3c508ac4"`);
        await queryRunner.query(`DROP TABLE "course_guest"`);
        await queryRunner.query(`DROP INDEX "IDX_275561ded9309f727f8e795bf1"`);
        await queryRunner.query(`DROP TABLE "course_tag"`);
        await queryRunner.query(`DROP TABLE "bbb_meeting"`);
    }

}
