export enum Subject {
    MATHEMATIK = 'Mathematik',
    DEUTSCH = 'Deutsch',
    ENGLISCH = 'Englisch',
    BIOLOGIE = 'Biologie',
    CHEMIE = 'Chemie',
    PHYSIK = 'Physik',
    INFORMATIK = 'Informatik',
    SACHKUNDE = 'Sachkunde',
    GESCHICHTE = 'Geschichte',
    ERDKUNDE = 'Erdkunde',
    WIRTSCHAFT = 'Wirtschaft',
    POLITIK = 'Politik',
    PHILOSOPHIE = 'Philosophie',
    KUNST = 'Kunst',
    MUSIK = 'Musik',
    PAEDAGOGIK = 'Pädagogik',
    FRANZOESISCH = 'Französisch',
    LATEIN = 'Latein',
    ALTGRIECHISCH = 'Altgriechisch',
    SPANISCH = 'Spanisch',
    ITALIENISCH = 'Italienisch',
    RUSSISCH = 'Russisch',
    NIEDERLAENDISCH = 'Niederländisch',
    DEUTSCH_ALS_ZWEITSPRACHE = 'Deutsch als Zweitsprache',
}
