export enum Language {
    sq = 'Albanisch',
    ar = 'Arabisch',
    hy = 'Armenisch',
    az = 'Aserbaidschanisch',
    bs = 'Bosnisch',
    bg = 'Bulgarisch',
    zh = 'Chinesisch',
    de = 'Deutsch',
    en = 'Englisch',
    fr = 'Französisch',
    it = 'Italienisch',
    kk = 'Kasachisch',
    ku = 'Kurdisch',
    pl = 'Polnisch',
    pt = 'Portugiesisch',
    ru = 'Russisch',
    tr = 'Türkisch',
    es = 'Spanisch',
    uk = 'Ukrainisch',
    vi = 'Vietnamesisch',
    other = 'Andere',
}
