export const testStudentSubjectsHistory = [
    {
        subject_name: 'Deutsch als Zweitsprache',
        mandatory_count: 15,
        grades: [
            '1. Klasse',
            '1. Klasse',
            '4. Klasse',
            '5. Klasse',
            '5. Klasse',
            '5. Klasse',
            '5. Klasse',
            '6. Klasse',
            '7. Klasse',
            '7. Klasse',
            '9. Klasse',
            '9. Klasse',
            '10. Klasse',
            '11. Klasse',
            '11. Klasse',
        ],
        historical_matches: 200,
    },
    {
        subject_name: 'Deutsch',
        mandatory_count: 11,
        grades: [
            '11. Klasse',
            '4. Klasse',
            '4. Klasse',
            '5. Klasse',
            '5. Klasse',
            '5. Klasse',
            '6. Klasse',
            '6. Klasse',
            '7. Klasse',
            '8. Klasse',
            '9. Klasse',
        ],
        historical_matches: 175,
    },
    {
        subject_name: 'Englisch',
        mandatory_count: 9,
        grades: ['4. Klasse', '6. Klasse', '6. Klasse', '6. Klasse', '6. Klasse', '8. Klasse', '9. Klasse', '10. Klasse', '11. Klasse'],
        historical_matches: 150,
    },
    {
        subject_name: 'Mathematik',
        mandatory_count: 8,
        grades: ['8. Klasse', '8. Klasse', '10. Klasse', '11. Klasse', '11. Klasse', '11. Klasse', '13. Klasse', '14. Klasse'],
        historical_matches: 125,
    },
    {
        subject_name: 'Rechnungswesen',
        mandatory_count: 2,
        grades: ['14. Klasse', '14. Klasse'],
        historical_matches: 11,
    },
    {
        subject_name: 'Chemie',
        mandatory_count: 2,
        grades: ['9. Klasse', '10. Klasse'],
        historical_matches: 8,
    },
    {
        subject_name: 'Informatik',
        mandatory_count: 1,
        grades: ['14. Klasse'],
        historical_matches: 1,
    },
    {
        subject_name: 'Französisch',
        mandatory_count: 0,
        grades: [],
        historical_matches: 17,
    },
    {
        subject_name: 'Wirtschaft',
        mandatory_count: 0,
        grades: [],
        historical_matches: 13,
    },
    {
        subject_name: 'Erdkunde',
        mandatory_count: 0,
        grades: [],
        historical_matches: 12,
    },
    {
        subject_name: 'Biologie',
        mandatory_count: 0,
        grades: [],
        historical_matches: 10,
    },
    {
        subject_name: 'Physik',
        mandatory_count: 0,
        grades: [],
        historical_matches: 9,
    },
    {
        subject_name: 'Spanisch',
        mandatory_count: 0,
        grades: [],
        historical_matches: 9,
    },
    {
        subject_name: 'Latein',
        mandatory_count: 0,
        grades: [],
        historical_matches: 7,
    },
    {
        subject_name: 'Pädagogik',
        mandatory_count: 0,
        grades: [],
        historical_matches: 4,
    },
    {
        subject_name: 'Lernen lernen',
        mandatory_count: 0,
        grades: [],
        historical_matches: 3,
    },
    {
        subject_name: 'Geschichte',
        mandatory_count: 0,
        grades: [],
        historical_matches: 2,
    },
    {
        subject_name: 'Gesundheit',
        mandatory_count: 0,
        grades: [],
        historical_matches: 2,
    },
    {
        subject_name: 'Sachkunde',
        mandatory_count: 0,
        grades: [],
        historical_matches: 1,
    },
    {
        subject_name: 'Technik',
        mandatory_count: 0,
        grades: [],
        historical_matches: 1,
    },
];

export const testPupilSubjectsHistory = [
    {
        subject: 'Deutsch',
        match_count: 300,
        median_days: 15,
        p90_days: 60,
    },
    {
        subject: 'Mathematik',
        match_count: 250,
        median_days: 5,
        p90_days: 25,
    },
    {
        subject: 'Deutsch als Zweitsprache',
        match_count: 200,
        median_days: 15,
        p90_days: 45,
    },
    {
        subject: 'Englisch',
        match_count: 100,
        median_days: 5,
        p90_days: 20,
    },
    {
        subject: 'Französisch',
        match_count: 15,
        median_days: 5,
        p90_days: 25,
    },
    {
        subject: 'Wirtschaft',
        match_count: 10,
        median_days: 6,
        p90_days: 22,
    },
    {
        subject: 'Erdkunde',
        match_count: 12,
        median_days: 20,
        p90_days: 49,
    },
    {
        subject: 'Rechnungswesen',
        match_count: 11,
        median_days: 9,
        p90_days: 35,
    },
    {
        subject: 'Biologie',
        match_count: 10,
        median_days: 4,
        p90_days: 16,
    },
    {
        subject: 'Physik',
        match_count: 9,
        median_days: 12,
        p90_days: 60,
    },
    {
        subject: 'Spanisch',
        match_count: 9,
        median_days: 38,
        p90_days: 53,
    },
    {
        subject: 'Chemie',
        match_count: 8,
        median_days: 5,
        p90_days: 12,
    },
    {
        subject: 'Latein',
        match_count: 7,
        median_days: 9,
        p90_days: 25,
    },
    {
        subject: 'Pädagogik',
        match_count: 4,
        median_days: 26,
        p90_days: 58,
    },
    {
        subject: 'Lernen lernen',
        match_count: 3,
        median_days: 3,
        p90_days: 3,
    },
    {
        subject: 'Gesundheit',
        match_count: 2,
        median_days: 12,
        p90_days: 21,
    },
    {
        subject: 'Geschichte',
        match_count: 2,
        median_days: 7,
        p90_days: 9,
    },
    {
        subject: 'Informatik',
        match_count: 1,
        median_days: 82,
        p90_days: 82,
    },
    {
        subject: 'Sachkunde',
        match_count: 1,
        median_days: 32,
        p90_days: 32,
    },
    {
        subject: 'Technik',
        match_count: 1,
        median_days: 2,
        p90_days: 2,
    },
];
